#!/bin/bash

# === USED TO UNPACK THE ORIGINAL uInitrd ===

if [ ! -f uInitrd.linux ]; then
  echo "uInitrd.linux not found!"
  exit 1
fi

mkdir ramfs.linux > /dev/null 2>&1
rm -rf ramfs.linux/* > /dev/null 2>&1
rm initrd.gz > /dev/null 2>&1
rm initrd > /dev/null 2>&1

# Strip off the 64 byte header:

dd if=uInitrd.linux of=initrd.gz bs=64 skip=1 > /dev/null 2>&1

# Uncompress and extract:

gunzip initrd.gz
cd ramfs.linux
cpio -i < ../initrd

cd ..
rm initrd > /dev/null 2>&1
rm initrd.gz > /dev/null 2>&1
