#!/bin/bash

if [ ! -d ramfs ]; then
  exit 1
fi

rm initrd.new > /dev/null 2>&1
rm initrd.new.gz > /dev/null 2>&1

cd ramfs
# Create and compress the cpio archive:

find | cpio -H newc -o > ../initrd.new
cd ..
gzip initrd.new

#Wrap up in a u-boot header:

mkimage -A arm -O linux -T ramdisk -C none -a 0 -e 0 -n initramfs -d initrd.new.gz uInitrd.multi

mv uInitrd.multi ../multiboot/uInitrd.multi

rm initrd.new > /dev/null 2>&1
rm initrd.new.gz > /dev/null 2>&1

